---
ports:
  dns: 192.168.1.84:53
  http: 192.168.1.84:4000

bootstrapDns:
  - tcp-tls:1.1.1.1:853
  - tcp-tls:1.0.0.1:853

upstreams:
  groups:
    default:
      - tcp-tls:1.1.1.1:853
      - tcp-tls:1.0.0.1:853
    river*:
      - tcp-tls:family.cloudflare-dns.com:853

clientLookup:
  upstream: &router 192.168.1.1

conditional:
  fallbackUpstream: false
  mapping:
    168.192.in-addr.arpa: *router
    internal: *router
    devbu.io: *router
    turbo.ac: *router

connectIPVersion: v4

caching:
  minTime: 15m
  prefetching: true
  cacheTimeNegative: -1

ecs:
  useAsClient: true

prometheus:
  enable: true
  path: /metrics

blocking:
  loading:
    downloads:
      timeout: 60s
  blackLists:
    ads:
      - https://big.oisd.nl/domainswild
      - |
        *.androidtvchannels-pa.googleapis.com
        *.androidtvwatsonfe-pa.googleapis.com
  whiteLists:
    ads:
      - |
        *.amazonaws.com
  clientGroupsBlock:
    default:
      - ads
