---
creation_rules:
  - path_regex: apps/.+\.sops\.env
    input_type: dotenv
    key_groups:
      - age:
          - age1nz0njhy3v78hfwu7cx330ngu5eafvu5wtfufe9r9rqu9hhqltpxs26ukw7
  - path_regex: apps/.+\.sops\.json
    input_type: json
    key_groups:
      - age:
          - age1nz0njhy3v78hfwu7cx330ngu5eafvu5wtfufe9r9rqu9hhqltpxs26ukw7
  - path_regex: apps/.+\.sops\.key
    input_type: json
    key_groups:
      - age:
          - age1nz0njhy3v78hfwu7cx330ngu5eafvu5wtfufe9r9rqu9hhqltpxs26ukw7
stores:
  yaml:
    indent: 2
