---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

env:
  SOPS_AGE_KEY_FILE: '{{.ROOT_DIR}}/age.key'
  TASK_TEMP_DIR: '{{.ROOT_DIR}}/.private'

vars:
  # renovate: datasource=github-releases depName=getsops/sops
  SOPS_VERSION: v3.8.1

includes:
  app: ./apps

tasks:

  default:
    silent: true
    cmd: go-task -l

  deps:
    desc: Install System Deps
    cmds:
      - sudo rpm-ostree install --idempotent --assumeyes age bind-utils direnv expect fastfetch fish fzf gh git go-task gron htop moreutils nano net-tools netcat nmap rsync systemd-networkd tcpdump telnet tree wget yq zoxide
      - sudo rpm-ostree install --idempotent --assumeyes https://github.com/getsops/sops/releases/download/{{.SOPS_VERSION}}/sops-{{.SOPS_VERSION | replace "v" ""}}.x86_64.rpm
      - sudo rpm-ostree install --idempotent --assumeyes https://downloads.1password.com/linux/rpm/stable/x86_64/1password-cli-latest.x86_64.rpm
      - # Direnv
        |
        mkdir -p /home/$LOGNAME/.config/direnv && \
        tee /home/$LOGNAME/.config/direnv/direnv.toml > /dev/null <<EOF
        [whitelist]
        prefix = [ "/var/opt/home-service" ]
        EOF
      - # Fish Hooks
        |
        tee /home/$LOGNAME/.config/fish/conf.d/hooks.fish > /dev/null <<EOF
        if status is-interactive
            if type -q direnv
                direnv hook fish | source
            end
            if type -q starship
                starship init fish | source
            end
            if type -q zoxide
                zoxide init fish | source
            end
        end
        EOF
      - # Fish Aliases
        |
        tee /home/$LOGNAME/.config/fish/conf.d/aliases.fish > /dev/null <<EOF
        alias task go-task
        EOF
      - # Fish Greeting
        |
        tee /home/$LOGNAME/.config/fish/conf.d/fish_greeting.fish > /dev/null <<EOF
        function fish_greeting
            fastfetch
        end
        EOF
      - # Fish Completions
        |
        curl -fsSL -o /home/$LOGNAME/.config/fish/completions/task.fish \
            https://raw.githubusercontent.com/go-task/task/main/completion/fish/task.fish
    preconditions:
      - msg: must not be run as root
        sh: '[[ $LOGNAME != "root" ]]'
