---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  tftpd: .taskfiles/tftpd

tasks:

  default:
    silent: true
    cmd: go-task -l

  deps:
    desc: Install System Deps
    cmds:
      - sudo rpm-ostree install --idempotent --assumeyes bind-utils git go-task htop nano net-tools netcat nmap moreutils rsync tcpdump telnet tree wget
      - curl -sL -o /tmp/1password-cli-latest.x86_64.rpm https://downloads.1password.com/linux/rpm/stable/x86_64/1password-cli-latest.x86_64.rpm
      - sudo rpm-ostree install /tmp/1password-cli-latest.x86_64.rpm
      - rm -rf /tmp/1password-cli-latest.x86_64.rpm

  start-*:
    desc: Start a container service
    cmds:
      - task: .reload
        vars: { container: "{{.container}}" }
      - sudo systemctl start {{.container}}
    vars:
      container: '{{index .MATCH 0}}'

  stop-*:
    desc: Stop a container service
    cmd: sudo systemctl stop {{.container}}
    vars:
      container: '{{index .MATCH 0}}'

  restart-*:
    desc: Restart a container service
    cmds:
      - task: .reload
        vars: { container: "{{.container}}" }
      - sudo systemctl restart {{.container}}
    vars:
      container: '{{index .MATCH 0}}'

  status-*:
    desc: Status of a container service
    cmd: sudo systemctl status {{.container}}
    vars:
      container: '{{index .MATCH 0}}'

  logs-*:
    desc: Tail logs of a container
    cmd: sudo podman logs -f {{.container}}
    vars:
      container: '{{index .MATCH 0}}'

  .reload:
    desc: Reload a container
    cmds:
      - sudo rsync -rv {{.ROOT_DIR}}/containers/{{.container}}/{{.container}}.container /etc/containers/systemd/
      - sudo rsync -rv --delete {{.ROOT_DIR}}/containers/{{.container}}/data/ /etc/containers/systemd/{{.container}}
      - sudo systemctl daemon-reload
    sources:
      - "{{.ROOT_DIR}}/containers/{{.container}}.container"
      - "{{.ROOT_DIR}}/containers/{{.container}}/data/config/**/**"
    generates:
      - /etc/containers/systemd/{{.container}}.container
      - /etc/containers/systemd/{{.container}}/config/**/**
      - /run/systemd/generator/{{.container}}.service
    label: reload-{{.container}}
    requires:
      vars: ["container"]
    internal: true
