---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  ROUTER_ADDR: 192.168.1.1

tasks:

  deps:
    desc: Download PXE files
    cmds:
      - curl -sL -o {{.ROOT_DIR}}/containers/tftpd/data/config/undionly.kpxe http://boot.ipxe.org/undionly.kpxe
      - curl -sL -o {{.ROOT_DIR}}/containers/tftpd/data/config/ipxe.efi http://boot.ipxe.org/ipxe.efi
      - curl -sL -o {{.ROOT_DIR}}/containers/tftpd/data/config/ipxe-arm64.efi https://boot.ipxe.org/arm64-efi/ipxe.efi

  pxe-hack:
    desc: Upload PXE config to Unifi router and restart dnsmasq
    cmds:
      - scp -r {{.ROOT_DIR}}/hack/ipxe.conf root@{{.ROUTER_ADDR}}:/run/dnsmasq.conf.d/ipxe.conf
      - ssh root@{{.ROUTER_ADDR}} "pkill dnsmasq"
